- name:  Copy repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo


- name:  rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest


- name:  Start rabbitmq server
  ansible.builtin.systemd_service:
    state: restarted
    name: rabbitmq-server
    enabled: true

- name:  create Application User and password and privileges
  ansible.builtin.shell: rabbitmqctl add_user {{ secrets.AMQP_USER }} {{ secrets.AMQP_PASS }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"





