- name: Setup Golang Service
  ansible.builtin.include_role:
    name: common
    tasks_from: golang





#dnf install golang -y
#useradd roboshop
#rm -rf /app
#mkdir /app
#curl -L -o /tmp/dispatch.zip https://roboshop-artifacts.s3.amazonaws.com/dispatch.zip
#cd /app
#unzip /tmp/dispatch.zip
#cd /app
#go mod init dispatch
#go get
#go build

#cp dispatch.service /etc/systemd/system/dispatch.service
#systemctl daemon-reload
#systemctl enable dispatch
#systemctl restart dispatch

