#app_path: /etc/yum.repos.d/rabbitmq.repo
component: rabbitmq
secrtes: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq token={{vault_token}} url=https://vault-internal.banecio-devops.online:8200 validate_certs=False')}}"